openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /convertDevise/convert/{fromCurrency}/{toCurrency}/{amount}:
    get:
      tags:
      - converdevise-controller
      operationId: convertDevise
      parameters:
      - name: fromCurrency
        in: path
        required: true
        schema:
          type: string
      - name: toCurrency
        in: path
        required: true
        schema:
          type: string
      - name: amount
        in: path
        required: true
        schema:
          type: number
          format: double
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ConvertResponse"
components:
  schemas:
    ConvertResponse:
      type: object
      properties:
        base_code:
          type: string
        target_code:
          type: string
        conversion_rate:
          type: number
          format: double
        amount:
          type: number
          format: double
        conversion_result:
          type: integer
          format: int32
