openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /toDoList/updateTodo/{id}:
    put:
      tags:
      - to-do-list-controller
      operationId: updateTodoList
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoList"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TodoList"
  /toDoList/addElem:
    post:
      tags:
      - to-do-list-controller
      operationId: add
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoList"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /toDoList/getOneTodo/{status}:
    get:
      tags:
      - to-do-list-controller
      operationId: getElemByStatus
      parameters:
      - name: status
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TodoList"
  /toDoList/getAllTodo:
    get:
      tags:
      - to-do-list-controller
      operationId: getAllTodoList
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TodoList"
  /toDoList/deleteTodo/{id}:
    delete:
      tags:
      - to-do-list-controller
      operationId: deleteElemById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
components:
  schemas:
    TodoList:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - a_faire
          - encours
          - termine
